### PR TITLE
open urls in new window

### PR DESCRIPTION
**Pull request by deanrather**
quick change to update Router.js so that double-clicking an element with a url will open the url in a new window.

### CODE REVIEW

**Comment by bensmithett** [comment]
Thank you! Released https://github.com/bensmithett/structurizr-mini/releases/tag/v1.1.0

---

I've generally avoided using `url` on elements myself because I don't love not knowing what a double-click will do until I do it. This will both open the URL in a new window and navigate down a level in the diagram (if it exists)

I think Structurizr itself opens up a modal and makes you choose if there's more than one possible link target for an element.

I'm not quite sure what the ideal UX is here. Please post any ideas or strong feelings in this thread and we might revisit.

**Comment by deanrather** [comment]
Structurizr Lite opens a drop-down menu and makes you choose, which I don't love because it kinda interrupts the "flow" of navigating around your diagrams.

This MR makes it open the new tab, but ALSO navigate. Which I think is a fine compromise...

As a QOL effort, in my diagrams I'm just not putting URLs on anything which has it's own diagram. eg: instead of having a URL on a container: I'll just put a single component in the container which has the URL on the component.
This way you can still navigate around, and the only urls are at the otherwise "dead-ends".

BTW You might be interested to know that I tried:
- LikeC4
- Structurizr Site Generatr
- Structurizr Lite
- Structurizr OnPrem

And I decided to go with Mini because of the two static-site options: it's the ONLY one which supports the workspace.json file with the manual layout info.

**Comment by bensmithett** [comment]
> I'm just not putting URLs on anything which has it's own diagram. eg: instead of having a URL on a container: I'll just put a single component in the container which has the URL on the component.
This way you can still navigate around, and the only urls are at the otherwise "dead-ends".

Nice workaround!

> it's the ONLY one which supports the workspace.json file with the manual layout info.

Out of curiosity if you can share, where's the source of truth for your manual layout into? Committed workspace.json, Structurizr Cloud, something else? Asking for myself :)

**Comment by deanrather** [comment]
> where's the source of truth for your manual layout info? Committed workspace.json, Structurizr Cloud, something else?

I'm still early on this journey, and haven't-yet got to the point where we have multiple contributors. At this point I'm the only person making updates, but many people are using/viewing it. It's also serving as an "index" of sorts to help find the relevant internal-wiki pages for each of the components.

Some of the diagrams are complicated-enough to warrant requiring manual layouts.

I tried the tips from your readme, and I was able to auto-generate the layouts by using the wrapper workspace, OR I was able to use the .json from structurizr-lite which had the manual layouts... but I was not able to make a workflow where I could auto-layout on some diagrams and manual-layout on other diagrams.

So my current workflow involves:

1) Use IDE to update the .yml
2) Use structurizr-lite to auto-layout the auto-layout pages, and manual-layout the manual-layout pages (generates .json)
3) git commit both the .yml and and .json
4) bundle the .json and structurizr-mini and deploy to secure intranet

**Pull request merged**
